- name: Configure MariaDB Repository
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.2/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
    state: present

- name: Creates MariaDB run directory
  file:
    path: /var/run/mariadb/
    recurse: yes
    state: directory
    mode: 0777

- name: Creates MariaDB log directory
  file:
    path: /var/log/mariadb/
    recurse: yes
    state: directory
    mode: 0777
