- hosts: all
  become: yes

  vars:
    nginx_sendfile: "off"
    nginx_remove_default_vhost: true

    nginx_vhosts:
      - listen: "80 default"
        server_name: "haydn.test"
        root: /var/www/haydn
        index: "index.php"
        extra_parameters: |
          include /var/www/haydn/nginx.conf;

    php_enablerepo: "remi,remi-php72"
    php_version: "7.2"
    php_enable_php_fpm: true
    php_expose_php: "Off"
    php_date_timezone: "Europe/Madrid"
    php_webserver_daemon: "{{ nginx_user }}"
    php_fpm_listen: /var/run/php-fpm/php-fpm.sock
    php_fpm_pool_user: "{{ nginx_user }}"
    php_fpm_pool_group: "{{ nginx_user }}"
    php_packages:
      - php
      - php-fpm
      - php-opcache
      - php-apcu

    php_opcache_enable_file_override: 1

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.nginx
    - geerlingguy.php

  post_tasks:
    - include_tasks: "{{ playbook_dir }}/tasks/php-fpm.yaml"
