- hosts: all
  become: yes

  vars:
    nginx_sendfile: "off"
    nginx_remove_default_vhost: true

    nginx_vhosts:
      - listen: "80 default"
        server_name: "haydn.test"
        root: /var/www/haydn
        index: "index.php"
        extra_parameters: |
          location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            # if (!-f $document_root$fastcgi_script_name) {
            #   return 404;
            # }
            fastcgi_index index.php;
            fastcgi_read_timeout 300;
            fastcgi_buffers 8 4k;
            fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            include fastcgi_params;
          }

          location ~ ^/index\.php(/|$) {
            fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            include fastcgi_params;
            internal;
          }

          location / {
            # try_files $uri /index.php$is_args$args;
            try_files $uri $uri/ /index.php$is_args$args;
          }

    php_enablerepo: "remi,remi-php70"
    php_version: "7.0"
    php_enable_php_fpm: true
    php_expose_php: "Off"
    php_date_timezone: "Europe/Madrid"
    php_webserver_daemon: "{{ nginx_user }}"
    php_fpm_listen: /var/run/php-fpm/php-fpm.sock
    php_fpm_pool_user: "{{ nginx_user }}"
    php_fpm_pool_group: "{{ nginx_user }}"
    php_packages:
      - php
      - php-fpm
    #   - php-opcache
    #   - php-apcu

    php_opcache_enable_file_override: 1

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.nginx
    - geerlingguy.php

  post_tasks:
    - include_tasks: "{{ playbook_dir }}/tasks/php-fpm.yaml"
